apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongman-tracker-api-deployment
  labels:
    app: strongman-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongman-tracker-api
  template:
    metadata:
      labels:
        app: strongman-tracker-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
      containers:
        - name: strongman-tracker-api
          image: zackaryclark/strongman-tracker-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "PORT"
              value: "8080"
            - name: "CLIENT_ORIGIN"
              valueFrom:
                secretKeyRef:
                  key: clientOrigin
                  name: strongman-tracker-secret
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  key: dbPort
                  name: strongman-tracker-secret
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  key: dbHost
                  name: strongman-tracker-secret
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  key: dbUserName
                  name: strongman-tracker-secret
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: dbUserPassword
                  name: strongman-tracker-secret
            - name: "KC_REALM"
              valueFrom:
                secretKeyRef:
                  key: kcRealm
                  name: strongman-tracker-secret
            - name: "KC_URL"
              valueFrom:
                secretKeyRef:
                  key: kcUrl
                  name: strongman-tracker-secret
            - name: "KC_RESOURCE"
              valueFrom:
                secretKeyRef:
                  key: kcResource
                  name: strongman-tracker-secret
            - name: "NODE_TLS_REJECT_UNAUTHORIZED"
              value: "0" # Only (sort of) acceptable because nginx ingress is doing our tls termination
